- name: Deploy LAMP Stack on localhost
  hosts: webservers
  become: true

  tasks:
    - name: Include Apache role
      import_role:
        name: apache

    - name: Include MySQL role
      import_role:
        name: mysql

    - name: Include PHP role
      import_role:
        name: php

    - name: Include firewall role
      import_role:
        name: firewall
