- name: Set MySQL root password
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: root
    password: "{{ mysql_root_password }}"
    host_all: true
    state: present

- name: Remove test database
  community.mysql.mysql_db:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: test
    state: absent

- name: Remove anonymous users
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: ''
    host_all: true
    state: absent

